### ISSUE TITLE
email_metrics should not be redefined in email_campaigns

### ISSUE THREAD

**Issue by leinemann** [fivetran/dbt_hubspot#39]
redefining the email_metrics var in email_campaigns causes the top level var to get ignored and hence causes failures when the user wants to disable for example `unsubscribes` from the dbt_project.yml.

https://github.com/fivetran/dbt_hubspot/blob/522c29b5553e9582337953865c59224f6eaf84dc/models/marketing/hubspot__email_campaigns.sql#L3

removing the email_metrics declaration above will fix the issue I blieve. And using `var('email_metrics')` instead.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann thank you for opening this issue! I have since created PR #40 to address this issue.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @leinemann this bug has been addressed and you will now be able to declare the variable appropriately within your `dbt_project.yml` without the `hubspot__email_campagins` model overriding the variable. The PR has since been merged and a new `v0.3.2` release of the package has been cut. You should see this new version of the package live on the [dbt hub](https://hub.getdbt.com/) most likely by Monday!

Thank you again!
